sudo: required
language: node_js
node_js:
- '14'
- '12'
- '10'
install:
- npm install lerna -g
- lerna bootstrap
script:
- lerna run compile
- lerna run test:coverage
- if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then lerna run coveralls; fi
- if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then lerna run codacy; fi
env:
  global:
  - secure: fMTLwwfm5nb7t0dP0HDoVBPprRUvGrs8VXwaTMqJvUn2jHjab8cbSo/Kkf7IAooMtSItk0NsXeH7YsZpjiEcXmEpwuHVgaRIGy0Kp0U6PXhtUNzAxiTi32/gR8HhyGUKRJpxH73A3LFVH9ybDlSUI5FNvAhtfwCjlYqiU/jiiwQfvlp/N52FwnN439rtx0leyHTOWMieTzltl7gJ1f7dNziQR2J0/aQeQYnjhy5VTXcYn0gJhJtvFWQ/A9IECbVmXcn/Qm9HQA3ooCYSO8bBrcuMxbs2TCDqHReudtRwhZNXIVZWryLYq9z2qAmG0kyxbjTlnol8FviDTHllfsqJnuT2denEwJZSelJwe0QPxYsQlI5Q8FktuE/q/O/Wqgq7LUZu83wVQO2hG5KEXCz5v24H8viVQ1pFe0WxJhaRvywB7oUimy4xZQ53v74YsJhFTmXvRlziuxVPXg+wYyaehGS1yo+k2UifJHJCPaabUu0D+0Scm1YI8TqIrEbP1aoVqMSrm9qALEGKXEXKQrOy4uum7tlXWNAFgESYOAx+wgpewHe5LGdBSUKha1AKSzyQRnlQXNTY/k4JRnwo/TLe35GVN0JAx78I23tw+uV7WL+bjDT95Lhm5lebSCyOOD2tDHxvNq9VVwyAw3xAU7aBRuupdWLM/eJ9/2K0L1T8OZA=
  - secure: XN0VoTOd+d6RINBNw3v3+kRnCBPat+kIgc11Z4CWpGQxkJWpvqCof0L1O/yhcxeLJuK1Kskh7qF+fob9N2pRDqw0tLlfpVmtyp4YF2PP4lj2TN6J1K8duPB9Y29COoVFb98CFjiyc4D22ByN6Ej6PAYoZrUbXXg/y+2vm6ATkjzJayhPgsFQ06/5vWSTzdaKiwBlnLDjzeUpID5XvOonxPOk/Xrjwp54zKzD1kPs1D5PBxB0QTZtMOSM4udvns95qWUvzXv+yfml9RC4rnFDiWrQkrnYAaN1yNW4Cd7xoR/TiFmtkBinhrrco/+giclz8YSwUkuv9rXMbvdF5hDUbB9rfCvxmue6F9Nz0KQ15EYV/iB3e4kO8vpS+d+/H295cRueU6+70HD7NpfSthE7xHdTxR9/8wPKAHMZq230YZHAxKZkDCII8C9yhBIvQ49hleocckrlBeajTXs36HSeCgtXjZ/JeLRZlQ9Y+Z/zNnKRq/Sm2C95CfEl/YRrNaEaB6eu34Y7lIGqKapU1ka3mENEJaoNjNFEbXupKPWQeb3Qg+ssChqPEalFhozVBNErLX2PJCMaxBxm9jZFTLtLkBAk9GBBDjgnofIayX3zhuymlS72t9ptEh1LjPLVlRUAwyiPOgw5odDh2lHJGh9fllq9q1bsbiSxHchvUTF1nao=
branches:
  only:
  - "/.*/"
