openapi: '3.0.0'
info:
  version: 1.0.0
  title: Swagger Petstore
  description: A sample API
  termsOfService: http://swagger.io/terms/
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
paths:
  /ping:
    get:
      operationId: ping.testing
      description: |
        ping then pong!
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: string
                example: pong
            application/json:
              schema:
                $ref: '#/components/schemas/pong'
                  
components:
  schemas:
    pong:
      properties:
        id:
          type: number
        ponged:
          type: boolean
      example:
        id: 1
        pong: true
